/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios;

/**
 *
 * @author juansergio
 */
public class BorderLayout extends javax.swing.JFrame {

    /**
     * Creates new form BorderLayout
     */
    public BorderLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BOTON3 = new javax.swing.JButton();
        BOTON1 = new javax.swing.JButton();
        BOTON5 = new javax.swing.JButton();
        BOTON4 = new javax.swing.JButton();
        BOTON2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BOTON3.setText("Button 3 (CENTER)");
        BOTON3.setToolTipText("");
        BOTON3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON3ActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON3, java.awt.BorderLayout.CENTER);

        BOTON1.setText("Button 1 (NORTH)");
        BOTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTON1ActionPerformed(evt);
            }
        });
        getContentPane().add(BOTON1, java.awt.BorderLayout.PAGE_START);

        BOTON5.setText("Button 5 (SOUTH)");
        getContentPane().add(BOTON5, java.awt.BorderLayout.PAGE_END);

        BOTON4.setText("Button 4 (EAST)");
        getContentPane().add(BOTON4, java.awt.BorderLayout.LINE_END);

        BOTON2.setText("Button 2 (WEST)");
        getContentPane().add(BOTON2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON1ActionPerformed

    private void BOTON3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTON3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTON3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorderLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTON1;
    private javax.swing.JButton BOTON2;
    private javax.swing.JButton BOTON3;
    private javax.swing.JButton BOTON4;
    private javax.swing.JButton BOTON5;
    // End of variables declaration//GEN-END:variables
}
