/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicios;

import javax.swing.JOptionPane;

/**
 *
 * @author juansergio
 */
public class JFieldPassword extends javax.swing.JFrame {

    /**
     * Creates new form JFieldPassword
     */
    public JFieldPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        opcional = new javax.swing.JTextField();
        sincambio = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introducir texto y pulsar enter");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        opcional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionalActionPerformed(evt);
            }
        });

        sincambio.setEditable(false);
        sincambio.setText("Campo no editable");
        sincambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sincambioActionPerformed(evt);
            }
        });

        contraseña.setText("jPasswordField1");
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(opcional, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(sincambio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(sincambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sincambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sincambioActionPerformed
        String cadena = "";
        if (evt.getSource() == nombre) {
            cadena = "nombre: " + evt.getActionCommand();
        } else if (evt.getSource() == opcional) {
            cadena = "opcional: " + evt.getActionCommand();
        } else if (evt.getSource() == sincambio) {
            cadena = "sincambio: " + evt.getActionCommand();
        } else if (evt.getSource() == contraseña) {
            cadena = "contraseña:" + evt.getActionCommand();
        }
        JOptionPane.showMessageDialog(
                null, cadena, "Resultados", JOptionPane.CANCEL_OPTION);


    }//GEN-LAST:event_sincambioActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        String cadena = "";
        if (evt.getSource() == nombre)
            cadena = "nombre: " + evt.getActionCommand();
        else if (evt.getSource() == opcional)
            cadena = "opcional: " + evt.getActionCommand();
        else if (evt.getSource() == sincambio)
            cadena = "sincambio: " + evt.getActionCommand();
        else if (evt.getSource() == contraseña) {
            cadena = "contraseña:" + evt.getActionCommand();
    }//GEN-LAST:event_nombreActionPerformed
        JOptionPane.showMessageDialog(
                null, cadena, "Resultados", JOptionPane.CANCEL_OPTION);

    }
    private void opcionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionalActionPerformed
        String cadena = "";
        if (evt.getSource() == nombre) {
            cadena = "nombre: " + evt.getActionCommand();
        } else if (evt.getSource() == opcional) {
            cadena = "opcional: " + evt.getActionCommand();
        } else if (evt.getSource() == sincambio) {
            cadena = "sincambio: " + evt.getActionCommand();
        } else if (evt.getSource() == contraseña) {
            cadena = "contraseña:" + evt.getActionCommand();
        }
        JOptionPane.showMessageDialog(
                null, cadena, "Resultados", JOptionPane.CANCEL_OPTION);
    }//GEN-LAST:event_opcionalActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        String cadena = "";
        if (evt.getSource() == nombre) {
            cadena = "nombre: " + evt.getActionCommand();
        } else if (evt.getSource() == opcional) {
            cadena = "opcional: " + evt.getActionCommand();
        } else if (evt.getSource() == sincambio) {
            cadena = "sincambio: " + evt.getActionCommand();
        } else if (evt.getSource() == contraseña) {
            cadena = "contraseña:" + evt.getActionCommand();
        }
        JOptionPane.showMessageDialog(
                null, cadena, "Resultados", JOptionPane.CANCEL_OPTION);


    }//GEN-LAST:event_contraseñaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFieldPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFieldPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFieldPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFieldPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFieldPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField opcional;
    private javax.swing.JTextField sincambio;
    // End of variables declaration//GEN-END:variables
}
